[package]
name = "tsangwu-gen-svc"
version.workspace = true
edition.workspace = true

[dependencies]
tsangwu-common = { workspace = true }
tsangwu-config = { workspace = true }
tsangwu-db = { workspace = true }
tsangwu-auth = { workspace = true }
tsangwu-cache = { workspace = true }
tsangwu-mq = { workspace = true }
tsangwu-storage = { workspace = true }
tsangwu-workflow = { workspace = true }
axum = { workspace = true }
sea-orm = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
