[package]
name = "tsangwu-template-svc"
version.workspace = true
edition.workspace = true

[dependencies]
tsangwu-common = { workspace = true }
tsangwu-config = { workspace = true }
tsangwu-db = { workspace = true }
tsangwu-auth = { workspace = true }
tsangwu-cache = { workspace = true }
axum = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
